[package]
name = "DicomReader"
version = "0.1.0"
authors = ["Michał Kluska <michal.kluska@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.1"
time ="*"

[dev-dependencies]
criterion = "0.2"
